spring.application.name=demoBackend
spring.data.mongodb.uri=${DB_URL:mongodb://pentaquest:example@localhost:27017}
spring.data.mongodb.database=pentaquest
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api/v1/docs
springdoc.swagger-ui.enabled=true